### ISSUE TITLE
[Bug]: Backtest tutorial contains an import which does not work

### ISSUE THREAD

**Issue by lfield** [quarkfin/qf-lib#129]
### Environment

```markdown
N/A
```

### What happened?

The backtest tutorial tries to import OnBeforeMarketOpenSignalGeneration but this no longer exists in the code base. 
https://github.com/quarkfin/qf-lib/blob/master/docs/source/tutorials/first_strategy_backtest.rst?plain=1#L201

### Screenshots

```bash
https://qf-lib.readthedocs.io/en/latest/tutorials/first_strategy_backtest.html#let-s-start-the-backtest
```

### Reproduction steps

```bash
https://qf-lib.readthedocs.io/en/latest/tutorials/first_strategy_backtest.html#let-s-start-the-backtest
```

**Comment by marekbais** [comment]
Thanks for raising the issue. The tutorial has been updated in https://github.com/quarkfin/qf-lib/pull/133 to match the demo script provided.
