### ISSUE TITLE
[Bug]: The installation docs doe not specify a Python version requirement.

### ISSUE THREAD

**Issue by lfield** [quarkfin/qf-lib#130]
### Environment

```markdown
N/A
```

### What happened?

The documentation should specify the Python version requirements and supported/tested OS versions.

https://qf-lib.readthedocs.io/en/latest/installation.html#prerequisites

Note that with github CI it should be possible to easily do install tests on many different OS. 

### Screenshots

```bash
https://qf-lib.readthedocs.io/en/latest/installation.html#prerequisites
```

### Reproduction steps

```bash
https://qf-lib.readthedocs.io/en/latest/installation.html#prerequisites
```

**Comment by marekbais** [comment]
Thanks for raising the issue. The documentation has been updated in https://github.com/quarkfin/qf-lib/pull/134 to include Python and OS requirements.
