### ISSUE TITLE
Error - demo script does not work....

### ISSUE THREAD

**Issue by stayhungry7** [quarkfin/qf-lib#39]
Hi there
I happened to find QF-lib, it seems to be good. useful advanced features 

When i try to run a demo app using qf-lib, i got this error.
I got codes from the demo-scripts, but it shows errors

The error line is below
    container = buildContainer()
    # ----- build trading session ----- #
    session_builder = container.resolve(BacktestTradingSessionBuilder)  # type: BacktestTradingSessionBuilder

please help me resolving this issue.

------------------------

def buildContainer():
    """
    Creates and returns the IoC container. If it already exists the existing instance is returned.
    WARNING: Container shall be used explicitly only in the scripts and NOWHERE ELSE!!! You better don't try to violate
    this rule or I'll find you.
    """

    builder = ContainerBuilder()
    #print('builder=',builder._container)
    
    # PUBLISHERS
    builder.register_class(EmailPublisher, component_scope=SingleInstance)

    # DATA PROVIDERS
    """
    builder.register_class(QuandlDataProvider, component_scope=SingleInstance)
    #builder.register_class(HaverDataProvider, component_scope=SingleInstance)
    builder.register_class(CryptoCurrencyDataProvider, component_scope=SingleInstance)
    """
    builder.register_class(BloombergDataProvider, component_scope=SingleInstance)    
    builder.register_class(GeneralPriceProvider, component_scope=SingleInstance)
        
    # MISCELLANEOUS COMPONENTS
    builder.register_class(BacktestTradingSessionBuilder, component_scope=SingleInstance)
    builder.register_class(RiskParityBoxesFactory, component_scope=SingleInstance)
    #builder.register_class(Settings, component_scope=SingleInstance)
    
    # EXPORTERS / IMPORTERS
    builder.register_class(ExcelExporter, component_scope=SingleInstance)
    builder.register_class(ExcelImporter, component_scope=SingleInstance)
    builder.register_class(PDFExporter, component_scope=SingleInstance)
    builder.register_class(HTMLExporter, component_scope=SingleInstance)
    builder.register_class(RealTimer, component_scope=SingleInstance, register_as=Timer)

 
    # OTHER
    #file_path = dirname(abspath(__file__))
    file_path = '/home/james/Workspace/Project/MyInvestment/src/working'
    settings_dir_path = join(file_path, 'config_files')
    settings_path = join(settings_dir_path, 'demo_settings.json')
    secret_path = join(settings_dir_path, 'demo_secret_settings.json')
    settings = Settings(settings_path, secret_path)
    
    return builder.build()

<ipython-input-36-364310120d9a> in test(container, data_provider)
    246 
    247     # ----- build trading session ----- #
--> 248     session_builder = container.resolve(BacktestTradingSessionBuilder)  # type: BacktestTradingSessionBuilder
    249     session_builder.set_backtest_name('Moving Average Alpha Model Backtest')
    250     session_builder.set_position_sizer(InitialRiskPositionSizer, initial_risk=initial_risk)

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in resolve(self, component_type, **kwargs)
    154         with self._resolve_lock:
    155             context = _ComponentContext(self)
--> 156             return context.resolve(component_type, **kwargs)
    157 
    158 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in resolve(self, component_type, **kwargs)
    128 
    129         registration = self._container.registry_map[component_type]
--> 130         return registration.create(self, kwargs)
    131 
    132 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in create(self, component_context, overriding_args)
     33         :return: An instance of the component.
     34         """
---> 35         return self.component_scope.instance(lambda: self._create(component_context, overriding_args))
     36 
     37 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/scope.py in instance(self, create_function)
     30     def instance(self, create_function):
     31         if self.component_instance is None:
---> 32             self.component_instance = create_function()
     33         return self.component_instance

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in <lambda>()
     33         :return: An instance of the component.
     34         """
---> 35         return self.component_scope.instance(lambda: self._create(component_context, overriding_args))
     36 
     37 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in _create(self, component_context, overriding_args)
     78             # not already provided, try resolve the argument
     79             if arg_name not in argument_map:
---> 80                 argument_map[arg_name] = component_context.resolve(arg_type)
     81 
     82         return self.class_type(**argument_map)

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in resolve(self, component_type, **kwargs)
    128 
    129         registration = self._container.registry_map[component_type]
--> 130         return registration.create(self, kwargs)
    131 
    132 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in create(self, component_context, overriding_args)
     33         :return: An instance of the component.
     34         """
---> 35         return self.component_scope.instance(lambda: self._create(component_context, overriding_args))
     36 
     37 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/scope.py in instance(self, create_function)
     30     def instance(self, create_function):
     31         if self.component_instance is None:
---> 32             self.component_instance = create_function()
     33         return self.component_instance

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in <lambda>()
     33         :return: An instance of the component.
     34         """
---> 35         return self.component_scope.instance(lambda: self._create(component_context, overriding_args))
     36 
     37 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in _create(self, component_context, overriding_args)
     78             # not already provided, try resolve the argument
     79             if arg_name not in argument_map:
---> 80                 argument_map[arg_name] = component_context.resolve(arg_type)
     81 
     82         return self.class_type(**argument_map)

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in resolve(self, component_type, **kwargs)
    128 
    129         registration = self._container.registry_map[component_type]
--> 130         return registration.create(self, kwargs)
    131 
    132 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in create(self, component_context, overriding_args)
     33         :return: An instance of the component.
     34         """
---> 35         return self.component_scope.instance(lambda: self._create(component_context, overriding_args))
     36 
     37 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/scope.py in instance(self, create_function)
     30     def instance(self, create_function):
     31         if self.component_instance is None:
---> 32             self.component_instance = create_function()
     33         return self.component_instance

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in <lambda>()
     33         :return: An instance of the component.
     34         """
---> 35         return self.component_scope.instance(lambda: self._create(component_context, overriding_args))
     36 
     37 

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in _create(self, component_context, overriding_args)
     78             # not already provided, try resolve the argument
     79             if arg_name not in argument_map:
---> 80                 argument_map[arg_name] = component_context.resolve(arg_type)
     81 
     82         return self.class_type(**argument_map)

~/anaconda3/envs/py38/lib/python3.8/site-packages/dic-1.5.2b1-py3.8.egg/dic/container.py in resolve(self, component_type, **kwargs)
    124         # normal component
    125         if component_type not in self._container.registry_map:
--> 126             raise DependencyResolutionError(
    127                 "The requested type %s was not found in the container. Is it registered?" % component_type.__name__)
    128 

DependencyResolutionError: The requested type Settings was not found in the container. Is it registered?

**Comment by myrmarachne** [comment]
Hi! The error "DependencyResolutionError: The requested type Settings was not found in the container. Is it registered?" means that the container could not find the "Settings" - you need to register it with e.g. register_instance - try the following:

```
...
settings = Settings(settings_path, secret_path)
builder.register_instance(Settings, settings)

return builder.build()
```
