### ISSUE TITLE
Development Environment Specification

### ISSUE THREAD

**Issue by guyfreund** [quarkfin/qf-lib#65]
Hi there, enjoyed reading your documentation, very elaborative!

I'm running Mac OSX 12.6 (M1) trying to set up a pipenv environment with the provided requirements file. I'm struggling to install all required versioned dependencies due to discrepancies. I found that problematic packages are arch, scikit-learn & statsmodels.

I was wondering if there might be an updated version of the dependencies versions. In addition, can you please elaborate on your python environment setup, e.g. what is the python versions manager (e.g. pyenv), and what tool do you use to handle python dependencies (e.g. pipenv).

Thanks in advance,
Guy

<img width="897" alt="image" src="https://user-images.githubusercontent.com/53565845/192282825-942c8b78-70f5-4d8e-a3d7-45c4706b8048.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/53565845/192282927-fda0ef09-e79a-4b23-92a3-180b385745a0.png">
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/53565845/192282990-4ae8123d-25fb-4741-9c3c-3057a83a1e12.png">

**Comment by guyfreund** [comment]
I found out that the following `requirement.txt` file passes all tests.

mac os users with apple silicon needs to follow https://github.com/cvxopt/cvxopt/issues/214 and https://github.com/cvxopt/cvxopt/issues/214#issuecomment-1260989925 for the last step.

`pandas==1.5.0
numpy==1.23.3
scipy==1.9.1
Pillow==9.2.0
MarkupSafe==2.1.1
matplotlib==3.6.0
joblib==1.2.0
scikit-learn==1.1.2
cvxopt==1.3.0
openpyxl==3.0.10
seaborn==0.12.0
weasyprint==56.1
emails==0.6
dic==1.5.2b1
Jinja2==3.1.2
arch==5.3.1
requests==2.28.1
statsmodels==0.13.2
xarray==2022.9.0
Quandl==3.7.0`

@myrmarachne can we change it officially?

**Comment by unmais** [comment]
Your comment has helped me set my own environment - Python 3.10 under Ubuntu. This is the `requirements.txt` that made it for me (made the unit test pass, no more than that):

`pandas==1.5.2
numpy==1.23.5
scipy==1.9.3
Pillow==9.3.0
MarkupSafe==2.1.1
matplotlib==3.6.2
joblib==1.2.0
scikit-learn==1.1.3
cvxopt==1.3.0
openpyxl==3.0.10
seaborn==0.12.1
weasyprint==57.1
emails==0.6
dic==1.5.2b1
Jinja2==3.1.2
arch==5.3.1
requests==2.28.1
statsmodels==0.13.5
xarray==2022.11.0
Quandl==3.7.0`

**Comment by myrmarachne** [comment]
Hi, we are adding support for python 3.10 and 3.11, along with the support for new dependencies in the next QF-Lib release.
